openapi: 3.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        count:
          type: number
        description:
          type: string
        price:
          type: number
        title:
          type: string
        category_id:
          type: number
info:
  title: QuestBook REST API
  description: QuestBook REST API
  version: '1'
paths:
  /product:
    get:
      operationId: getProductsList
      summary: Product list
      description: Get product list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: A user information object
      parameters: []
      responses:
        '200':
          description: A user object along with generated API Keys
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: An error message when creating a new user
          content: {}
